Show md5sum of tested files

diff --git a/tests/test-all b/tests/test-all
--- a/tests/test-all
+++ b/tests/test-all
@@ -31,9 +31,10 @@ trap cleanup EXIT
 rc=0
 for i in "${fonts[@]}"; do
 	md5sum=$(echo $i | md5sum | awk '{print $1}')
+	echo -n "Testing md5=${md5sum} for $i"
 	eval "${ft}" $i -t "\"${str}\"" > "${tmp}"
-	cmp --quiet "${tmp}" "${datadir}/${md5sum}" || (
-		echo "ERROR: Font failed compare: $i" >&2;
+	cmp "${tmp}" "${datadir}/${md5sum}" || (
+		echo -n "ERROR: Font failed compare: ${md5sum} $i" >&2;
 		exit 1) || rc=1
 done
 
